# permissions for end users to edit tailscalek3sagents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tailscale-k3s-operator
    app.kubernetes.io/managed-by: kustomize
  name: tailscalek3sagent-editor-role
rules:
- apiGroups:
  - nodes.visionbyscope.com
  resources:
  - tailscalek3sagents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nodes.visionbyscope.com
  resources:
  - tailscalek3sagents/status
  verbs:
  - get
