apiVersion: nodes.visionbyscope.com/v1alpha1
kind: TailscaleK3sAgent
metadata:
  labels:
    app.kubernetes.io/name: tailscale-k3s-operator
  name: tailscalek3sagent-sample
spec:
  k3sServerURL: "https://k3s-server:6443"
  k3sToken: "your-k3s-token"
  clientId: "${CLIENT_ID}"
  clientSecret: "${CLIENT_SECRET}"
  tailscaleOrgName: "visionbyscope.com"
  tags:
    - "tag:k3s"
    - "tag:production"
